### ISSUE TITLE
Handling of multiple links in one line failed

### ISSUE THREAD

**Issue by hklausing** [dopsi/mdl#2]
If I have multiple links in one line than only the first link will be displayed. Following is an example:
    Test line: [google.com](https://google.com) and the next link [amazon.com](https://amazon.com).
will output the line:
    Test line: google.com[1].

The listed link can not be used on my system. I guess parsing the first URL stops at the end of last URL.

BR
   Heiko

**Comment by dopsi** [comment]
Thanks for reporting this, the new commit should fix the issue (it does on my end).
